version: '3.5'
services:
  valorant-watcher:
    image: thisnoah/valorant-watcher:latest
    container_name: valorant-watcher
    restart: always
    environment:
      - token=rxk38rh5qtyw95fkvm7kgfceh4mh6u
      - timeout=5000000
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- scrollDelay=2000
      #- scrollTimes=5
      #- minWatching=6
      #- maxWatching=15
      #- streamerListRefres=2
      #- streamerListRefreshUnit=hour
      #- browserScreenshot=false
    #volumes:
    #  - "./screenshots:/usr/src/app/screenshots"
